### ISSUE TITLE
Weirdly enough, this extension is not finding its own Intelephense installation

### ISSUE THREAD

**Issue by GwynethLlewelyn** [GeneaLabs/panic-nova-intelephense.novaextension#1]
Hi @mikebronner 👋

Recently I noticed that your Intelephense extension stopped working (I cannot pinpoint exactly _when_ that first happened, but my guess is that it stopped working around the time Nova upgraded to 8; I'm currently running Nova 8.3 [Build 343365] under macOS Big Sur 11.6.3 [20G405]).

These are the logs I get (restarting the extension will basically print out the same errors, just on a different workspace storage path). Note that the red exclamation mark is the closest I could come with a symbol that marks the error in Nova (the white exclamation mark inside a red circle).

```
   Intelephense[20:14:43.906000] Creating extension workspace storage path: /Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense
   Intelephense[20:14:43.906000] Creating extension global storage path: /Users/gwyneth/Library/Application Support/Nova/Extensions/genealabs.intelephense
   Intelephense[20:14:43.906000] Creating Intelephense workspace storage path: /Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/intelephense
   Intelephense[20:14:43.906000] Creating Intelephense global storage path: /Users/gwyneth/Library/Application Support/Nova/Extensions/genealabs.intelephense/intelephense
   Intelephense[20:14:44.899000] Starting Intelephense installation.
❗️ Intelephense LSP[20:14:48.626000] node:internal/modules/cjs/loader:936
❗️ Intelephense LSP[20:14:48.626000]   throw err;
❗️ Intelephense LSP[20:14:48.626000]   ^
❗️ Intelephense LSP[20:14:48.626000] 
❗️ Intelephense LSP[20:14:48.626000] Error: Cannot find module '/Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/node_modules/intelephense/lib/intelephense.js'
❗️ Intelephense LSP[20:14:48.627000]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
❗️ Intelephense LSP[20:14:48.627000]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
❗️ Intelephense LSP[20:14:48.627000]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
❗️ Intelephense LSP[20:14:48.627000]     at node:internal/main/run_main_module:17:47 {
❗️ Intelephense LSP[20:14:48.627000]   code: 'MODULE_NOT_FOUND',
❗️ Intelephense LSP[20:14:48.627000]   requireStack: []
❗️ Intelephense LSP[20:14:48.627000] }
❗️ Intelephense LSP[20:14:48.627000] 
❗️ Intelephense LSP[20:14:48.627000] Node.js v17.3.0
```

I have looked through your code just very superficially, so I might be completely out of my league here, but I believe that, for some reason, `npm` is failing to create the required `node_modules` directory inside the workspace.

Indeed, the directory `/Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/intelephense` _does_ exist — i.e. it _was_ properly created, with 755 permissions (which is about right) and the correct user owning it.

Now, I have several possible explanations for this behaviour, but sadly I cannot figure out to fix them, even if my hypothesis were correct...

1. I'm currently running PHP 8.1. While this ought not to interfere with `npm`, your README explicitly mentions that Intelephense does not yet support PHP 8+. For my purposes, it's pretty much irrelevant; while I use some very minor things that appeared in 7.3 or 7.4, I _mostly_ stick to 'old school' PHP, so I wouldn't really worry much about the lack of support for 8+. And the errors on the Nova log do not seem to point to _that_, anyway...
2. Almost all CLI software I've got on my Mac (and some of the GUI-based as well) has been installed via Homebrew. In particular, `nodejs` and `npm` — because I'm not overly familiar with hard-core JavaScript coding — have been installed, but for many months (years?) I have long suspected that there is something wrong with the configuration. Ironically, I only noticed that when installing one Nova extension, which looked for the installed `npm` binary in the _right_ place, but... it wasn't there! (Every time  either`nodejs` or `npm` get upgraded, I need to remember to add a symbolic link for `npm`). This _could_ have some consequences for your code, which may be expecting a rational layout for `nodejs`, and my Mac just happens to have a very messy installation (but, as said, I don't know how to fix it!).

Also, I wonder if there is a way to use the system-wide Intelephense installation, instead of getting Nova to install its own...

Anyway, any insights into this would be most appreciated! Thanks so much in advance!

**Comment by mikebronner** [comment]
Hi @GwynethLlewelyn, thanks for writing in, good to hear from you! I have been absent from the Nova community for the past year or so, as I just spend too much time trying to fix things in Nova packages, and can never get Nova configured as I would like it. I'm doing all my development on remote dev servers, something that Nova doesn't really support either. (I'm back on VSCode, although I would much prefer a native app like Nova -- I had high hopes for it, but my use-case is a bit outside of its scope.)

I think Nova changed how the bootstrapping of language providers works in version 8, and I have not kept up. My apologies for the inconveniences caused. I don't have a quick answer for you at the moment, other than perhaps trying reykjalin's Intelphense package -- not sure if that works or not, either. We didn't have much luck getting Intelephense to run correctly on Nova's language server API, but maybe that has changed now with Nova 8? Once can hope.

**Comment by GwynethLlewelyn** [comment]
... oh, and just for the sake of completeness, I _did_ simply copy the system-wide Intelephense install to the path that your extension expects it, just to understand if it was merely an issue with _installing_ it from within Nova.

Interestingly, these are the logs...

```
Intelephense LSP[20:57:34.125000] /Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/node_modules/intelephense/lib/intelephense.js:3
Intelephense LSP[20:57:34.293000] is.authority),this.query&&(e.query=this.query),this.fragment&&(e.fragment=this.fragment),e},t}(f),g=((i={})[58]="%3A",i[47]="%2F",i[63]="%3F",i[35]="%23",i[91]="%5B",i[93]="%5D",i[64]="%40",i[33]="%21",i[36]="%24",i[38]="%26",i[39]="%27",i[40]="%28",i[41]="%29",i[42]="%2A",i[43]="%2B",i[44]="%2C",i[59]="%3B",i[61]="%3D",i[32]="%20",i);function _(e,t){for(var n=void 0,r=-1,i=0;i<e.length;i++){var a=e.charCodeAt(i);if(a>=97&&a<=122||a>=65&&a<=90||a>=48&&a<=57||45===a||46===a||95===a||126===a||t&&47===a)-1!==r&&(n+=encodeURIComponent(e.substring(r,i)),r=-1),void 0!==n&&(n+=e.charAt(i));else{void 0===n&&(n=e.substr(0,i));var o=g[a];void 0!==o?(-1!==r&&(n+=encodeURIComponent(e.substring(r,i)),r=-1),n+=o):-1===r&&(r=i)}}return-1!==r&&(n+=encodeURIComponent(e.substring(r))),void 0!==n?n:e}function y(e){for(var t=void 0,n=0;n<e.length;n++){var r=e.charCodeAt(n);35===r||63===r?(void 0===t&&(t=e.substr(0,n)),t+=g[r]):void 0!==t&&(t+=e[n])}return void 0!==t?t:e}function v(e,t){var n;return 

... full dump of intelephense.js here in the Nova logs...

Intelephense LSP[20:57:34.345000]     at /Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/node_modules/intelephense/lib/intelephense.js:3:168725
Intelephense LSP[20:57:34.345000]     at /Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/node_modules/intelephense/lib/intelephense.js:3:169019
Intelephense LSP[20:57:34.345000]     at Immediate.<anonymous> (/Users/gwyneth/Library/Application Support/Nova/Workspaces/5901757A-1876-40A2-A83F-89948CB68871/genealabs.intelephense/node_modules/intelephense/lib/intelephense.js:3:169378)

```

That's not very useful, I guess, but I also get similar errors when manually launching the system-wide installed Intelephense directly from the Homebrew-installed `nodejs`...

**Comment by mikebronner** [comment]
@GwynethLlewelyn I'm finally back in Nova land again and have gotten my extensions running again. I have a bit more work to do on the Intelephense extension by providing all the configuration options, but will have that in soon.

Now that I got my Mac Studio, I can go nuts with Docker containers locally and develop locally again.

(At the moment we're using SSH to develop remotely on servers, which is working out great in VSCode, but not for Nova)

**Comment by GwynethLlewelyn** [comment]
Hi @mikebronner! So glad to see you around again :-)

I promptly downloaded your latest version and hurried to test it out — I've got a project which is _mostly_ C# (ugh) but has some PHP in it, which gets flagged by GitHub Actions as being horribly out of date. Time to get some Intelephense magic! 😹 

Sadly, however, it seems that I'm stuck with precisely the same errors as before.

Notice how your extension, when creating things on a new workplace under `Library/Application Support/Nova/Workspaces/<UUID>`, will create (correctly) the directory `genealabs.intelephense`, but inside it, it places everything under the directory `intelephense`— while `nodejs` is **expecting** to find a `node_modules` directory first!

Worse than that: the directory `intelephense`, in my system, is _empty_. Weird, huh?

All right, it was time for me to fork your code and take a peek at it :-) Fortunately, you write _clean_, understandable code (as opposed to, uh, some of our fellow Nova extension developers, which shall remain unnamed because I don't want to sound offensive, or, worse, condescending...), and it's also very short, so I managed to spend a few hours hacking at it.

The first thing I noticed was some inconsistency in the way the directories were being called/named. I'm not quite sure if that was intentional or not, but you have defined `workspaceStoragePath` right at the beginning (to include not only the extension name in the workplace space, but a new directory under it, `intelephense` — an approach that seems quite reasonable to me), but... somehow, this variable gets called inconsistently. Sometimes you use it, sometimes you don't, and I was confused why you made some of the choices... so, I decided to use `workspaceStoragePath` for _everything_, and hoped for the best!

Well, that wasn't enough.

Now, I have absolutely no idea if this is something that only happens in _my_ case, but `npm` refuses to install anything on a specific directory **unless it has a `project.json` in it**. I'm not sure if that's by design or by choice or by mistake or just because I'm really too clueless about how `npm` is expected to work, but... my point is, with the `npm` straight out of `brew install npm` (possibly if one installs `npm` in other ways, the issue I have does not occur — I don't know!), it only works that way. No matter where in the filesystem I am, by default, it _always_ attempts to use the `project.json` which I've got on my home directory (let's call it 'my local configuration'), unless, of course, I pass it a `--global` flag.

In the case of your extension, Intelephense clearly should _not_ be globally installed — there is no need for that, unless the user _also_ uses Intelephense someplace else (and if you're using Nova... you won't be using any other tool. Heh! 😁 ). So, the correct way is to do it exactly as you did (again, IMHO, I'm not an expert...): install Intelephense on a local directory under the control of the Nova ecosystem, and run it from there, for as long as the user wants to use your extension; and clean up afterwards.

Well, I have no idea if I have 'broken' my `npm` configuration at some point, but the truth is, from what I read on the online `npm` manuals (very, very briefly! I didn't spend much time on that...), `npm` is _supposed_ to always work in conjunction with a `project.json`. You _can_, however, instruct `npm` to generate one by default, with reasonable defaults, a process that can be either interactive or automated (basically, replying 'yes' to all questions...).

So, I gave it a try. I changed your code to create a `project.json` file on the directory that `npm` expects to find it — `workspaceStoragePath`, that is — with some reasonable defaults (mostly using data extracted from `nova.extension.xxx` information, and the rest hard-coded.

Guess what? Everything worked flawlessly on the first attempt! :-) Expect a PR shortly!

Again — I'm not really sure if the problem is simply because I have somehow misconfigured `npm` in some obscure way, which is perfectly possible. I'm also not sure if there isn't a more elegant way to deal with this. The truth is that, _in my case_, while working on the PR, as soon as I activated Intelephense with my changes, I started getting lots of notifications on my _other_ windows, where I had a few PHP scripts, alerting me for a series of small issues that I had overlooked... lol. I didn't even _switch_ to those windows, they were happily running in the background, Nova automagically activated the 'new' extension for all of them, and all of them worked (I'm sort of 'upgrading' ancient PHP 4/5 code to 7/8... so you can imagine there will be lots of deprecated functions and obscure errors...).

Anyway, as always, look carefully at whatever code I've submitted, I'm not a JS programmer, there might be much better ways to accomplish the same thing, and, as said, it might be worth checking out _if_ `npm` is behaving in the 'expected' way first. I'm assuming that, since everything works in your own setup, it means that _I_ have something wrongly configured somewhere — and it might be easy for you to figure out what you expect to be the correct `npm` installation first, and, if the extension detects that something is wrong with it, _then_ it executes the code that adds the required `project.json` in the correct place (maybe there is even an option for `npm` to work _without_ a `project.json`...?).

Also, please take a look at the directories where you're placing things. For instance, testing for an empty directory (which ought to have a `node_modules` inside, allegedly created by `npm` during the installation procedure...) should be a quick fix to at least alert the user that something is wrong.

My wishlist for 1.9.0: add the possibility for using the _global_ `npm` installation of Intelephense, as an option (just like you have for your other extensions!)...

Cheers, happy code reviewing ;-)

**Comment by mikebronner** [comment]
@GwynethLlewelyn   Thanks for you VERY detailed response!!! :) I have been running it successfully on my machine, but I may have some pre-existing settings outside of Nova that satisfied those requirements.

**Comment by GwynethLlewelyn** [comment]
> @GwynethLlewelyn Thanks for you VERY detailed response!!! :) I have been running it successfully on my machine, but I may have some pre-existing settings outside of Nova that satisfied those requirements.

Perhaps you could add those to the README.md... I don't know, it's just a suggestion! And in that case you could ignore PR #2 completely :)

**Comment by mikebronner** [comment]
For sure! I just have to identify exactly what those are :)

**Comment by mikebronner** [comment]
@GwynethLlewelyn if you did want to take a stab at a PR, that would be awesome, even if it just for me to see the changes you made, so that I can make sense of what you had going on

**Comment by GwynethLlewelyn** [comment]
Done :) See #2 :)

**Comment by GwynethLlewelyn** [comment]
Yay! Thanks 🥇
